server:
  port: 8084
spring:
  application:
    name: OnlineJudge

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect

jwt:
  secret: ${JWT_SECRET}


#  security:
#    user:
#      name: anmol.jain
#      password: ajin123
#      roles: USER